'use client';
import {
  Globe, Smartphone, Cpu, Database, HardDrive, Heart, Users, CreditCard, Package,
  Headphones, Phone, ShoppingCart, Mail, Megaphone, MousePointer, FileText,
  Fingerprint, Search, FlaskConical, BarChart3, TestTube, Zap, Clock
} from 'lucide-react';

// ─── Full MDF Data Source Catalog (25+ sources) ──────────────────────────────

export const SOURCE_CATALOG = [
  // ── A) Digital Properties / Behavioral ──────────────────────────────────────
  {
    id: 'webAppEvents',
    name: 'Web/App Events (SDK)',
    description: 'Tag-based click, scroll, form events',
    icon: Globe,
    color: '#06b6d4',
    dataClass: 'behavioral',
    identitiesAvailable: ['cookie_id', 'device_id', 'email'],
    ingestionMode: 'realtime',
    exampleFields: ['event_name', 'page_url', 'session_id', 'timestamp'],
    sourceCategory: 'Digital Property',
  },
  {
    id: 'mobileAppEvents',
    name: 'Mobile App Events',
    description: 'In-app actions, push tokens, screen views',
    icon: Smartphone,
    color: '#06b6d4',
    dataClass: 'behavioral',
    identitiesAvailable: ['device_id', 'email', 'push_token'],
    ingestionMode: 'realtime',
    exampleFields: ['screen_name', 'action', 'app_version', 'os'],
    sourceCategory: 'Digital Property',
  },
  {
    id: 'productTelemetry',
    name: 'Product Usage / Telemetry',
    description: 'SaaS feature adoption, usage frequency',
    icon: Cpu,
    color: '#06b6d4',
    dataClass: 'behavioral',
    identitiesAvailable: ['user_id', 'email'],
    ingestionMode: 'batch',
    exampleFields: ['feature_name', 'usage_count', 'session_duration', 'plan_tier'],
    sourceCategory: 'Digital Property',
  },

  // ── B) Data Infrastructure (EDW / 1st Party) ───────────────────────────────
  {
    id: 'edw',
    name: 'Enterprise Data Warehouse',
    description: 'Consolidated structured data from ERP/Finance',
    icon: Database,
    color: '#f59e0b',
    dataClass: 'transactional',
    identitiesAvailable: ['customer_id', 'crm_id', 'email'],
    ingestionMode: 'batch',
    exampleFields: ['account_id', 'revenue', 'segment', 'region'],
    sourceCategory: 'Data Infrastructure',
  },
  {
    id: 'dataLake',
    name: 'Data Lake (Behavior + Media)',
    description: 'Raw behavioral and paid media logs',
    icon: HardDrive,
    color: '#f59e0b',
    dataClass: 'behavioral',
    identitiesAvailable: ['cookie_id', 'device_id', 'click_id'],
    ingestionMode: 'batch',
    exampleFields: ['event_type', 'referrer', 'utm_params', 'raw_payload'],
    sourceCategory: 'Data Infrastructure',
  },
  {
    id: 'loyalty',
    name: 'Loyalty / Membership System',
    description: 'Points, tiers, rewards redemptions',
    icon: Heart,
    color: '#f59e0b',
    dataClass: 'transactional',
    identitiesAvailable: ['loyalty_id', 'email', 'phone'],
    ingestionMode: 'batch',
    exampleFields: ['points_balance', 'tier', 'last_redemption', 'join_date'],
    sourceCategory: 'Data Infrastructure',
  },
  {
    id: 'customerMDM',
    name: 'Customer Master / MDM',
    description: 'Master data management golden source',
    icon: Users,
    color: '#f59e0b',
    dataClass: 'transactional',
    identitiesAvailable: ['master_id', 'crm_id', 'email', 'phone'],
    ingestionMode: 'batch',
    exampleFields: ['full_name', 'address', 'segment', 'lifecycle_stage'],
    sourceCategory: 'Data Infrastructure',
  },
  {
    id: 'billing',
    name: 'Billing / Subscription System',
    description: 'Invoices, MRR, churn signals',
    icon: CreditCard,
    color: '#f59e0b',
    dataClass: 'transactional',
    identitiesAvailable: ['customer_id', 'email'],
    ingestionMode: 'batch',
    exampleFields: ['plan_name', 'mrr', 'billing_cycle', 'payment_status'],
    sourceCategory: 'Data Infrastructure',
  },
  {
    id: 'oms',
    name: 'Order Management System',
    description: 'Order lifecycle, fulfillment, returns',
    icon: Package,
    color: '#f59e0b',
    dataClass: 'transactional',
    identitiesAvailable: ['order_id', 'customer_id', 'email'],
    ingestionMode: 'batch',
    exampleFields: ['order_id', 'status', 'total', 'shipping_method'],
    sourceCategory: 'Data Infrastructure',
  },

  // ── C) Customer-Centric ─────────────────────────────────────────────────────
  {
    id: 'crm',
    name: 'CRM (Salesforce)',
    description: 'Leads, contacts, opportunities',
    icon: Users,
    color: '#8b5cf6',
    dataClass: 'transactional',
    identitiesAvailable: ['crm_id', 'email', 'phone'],
    ingestionMode: 'batch',
    exampleFields: ['lead_score', 'status', 'owner', 'last_activity'],
    sourceCategory: 'Customer Centric',
  },
  {
    id: 'pos',
    name: 'POS / Commerce (Shopify)',
    description: 'Orders, products, revenue',
    icon: ShoppingCart,
    color: '#8b5cf6',
    dataClass: 'transactional',
    identitiesAvailable: ['customer_id', 'email', 'phone'],
    ingestionMode: 'batch',
    exampleFields: ['order_total', 'products', 'payment_method', 'store_id'],
    sourceCategory: 'Customer Centric',
  },
  {
    id: 'support',
    name: 'Customer Support (Zendesk)',
    description: 'Tickets, CSAT scores, resolution times',
    icon: Headphones,
    color: '#8b5cf6',
    dataClass: 'event',
    identitiesAvailable: ['email', 'phone', 'customer_id'],
    ingestionMode: 'batch',
    exampleFields: ['ticket_id', 'subject', 'priority', 'csat_score'],
    sourceCategory: 'Customer Centric',
  },
  {
    id: 'callCenter',
    name: 'Call Center / IVR Logs',
    description: 'Inbound/outbound calls, dispositions',
    icon: Phone,
    color: '#8b5cf6',
    dataClass: 'event',
    identitiesAvailable: ['phone', 'customer_id'],
    ingestionMode: 'batch',
    exampleFields: ['call_duration', 'disposition', 'agent_id', 'queue_time'],
    sourceCategory: 'Customer Centric',
  },

  // ── D) Marketing & Advertising ──────────────────────────────────────────────
  {
    id: 'emailEngagement',
    name: 'Email Engagement Data',
    description: 'Opens, clicks, unsubscribes across campaigns',
    icon: Mail,
    color: '#ec4899',
    dataClass: 'marketing',
    identitiesAvailable: ['email', 'subscriber_id'],
    ingestionMode: 'batch',
    exampleFields: ['campaign_id', 'opens', 'clicks', 'bounced'],
    sourceCategory: 'Marketing',
  },
  {
    id: 'paidSocial',
    name: 'Paid Social / Search',
    description: 'Meta Ads, Google Ads, LinkedIn campaigns',
    icon: Megaphone,
    color: '#ec4899',
    dataClass: 'marketing',
    identitiesAvailable: ['click_id', 'device_id'],
    ingestionMode: 'realtime',
    exampleFields: ['campaign', 'ad_platform', 'spend', 'impressions'],
    sourceCategory: 'Marketing',
  },
  {
    id: 'adImpressions',
    name: 'Ad Impressions / Click Logs',
    description: 'Programmatic display, DSP logs',
    icon: MousePointer,
    color: '#ec4899',
    dataClass: 'marketing',
    identitiesAvailable: ['device_id', 'cookie_id'],
    ingestionMode: 'realtime',
    exampleFields: ['creative_id', 'placement', 'viewability', 'ctr'],
    sourceCategory: 'Marketing',
  },
  {
    id: 'offlineCampaigns',
    name: 'Offline Campaign Lists',
    description: 'Direct mail, event attendees, trade shows',
    icon: FileText,
    color: '#ec4899',
    dataClass: 'marketing',
    identitiesAvailable: ['email', 'phone', 'name'],
    ingestionMode: 'batch',
    exampleFields: ['campaign_name', 'list_source', 'response_flag', 'event_date'],
    sourceCategory: 'Marketing',
  },
  {
    id: 'marketo',
    name: 'Marketing Automation (Marketo)',
    description: 'Email engagement, nurture campaigns',
    icon: Mail,
    color: '#ec4899',
    dataClass: 'marketing',
    identitiesAvailable: ['email', 'marketo_id'],
    ingestionMode: 'batch',
    exampleFields: ['email_opens', 'email_clicks', 'last_campaign', 'subscribed'],
    sourceCategory: 'Marketing',
  },

  // ── E) Identity & Enrichment ────────────────────────────────────────────────
  {
    id: 'identityGraph',
    name: 'Identity Graph Provider',
    description: 'Cross-device and cross-channel ID linkage',
    icon: Fingerprint,
    color: '#10b981',
    dataClass: 'event',
    identitiesAvailable: ['hashed_email', 'device_id', 'household_id'],
    ingestionMode: 'batch',
    exampleFields: ['id_cluster', 'confidence', 'link_type', 'last_seen'],
    sourceCategory: 'Identity & Enrichment',
  },
  {
    id: 'enrichment',
    name: 'Enrichment Provider (ZoomInfo)',
    description: 'Firmographic, technographic, intent data',
    icon: Search,
    color: '#10b981',
    dataClass: 'event',
    identitiesAvailable: ['email', 'domain', 'company_id'],
    ingestionMode: 'batch',
    exampleFields: ['company_name', 'industry', 'employee_count', 'tech_stack'],
    sourceCategory: 'Identity & Enrichment',
  },
  {
    id: 'cleanRoom',
    name: 'Data Clean Room Inputs',
    description: 'Aggregated datasets from partners (privacy-safe)',
    icon: FlaskConical,
    color: '#10b981',
    dataClass: 'event',
    identitiesAvailable: ['hashed_email', 'segment_id'],
    ingestionMode: 'batch',
    exampleFields: ['partner_name', 'audience_segment', 'overlap_count', 'match_rate'],
    sourceCategory: 'Identity & Enrichment',
  },

  // ── F) Analytics & Measurement ──────────────────────────────────────────────
  {
    id: 'ga4',
    name: 'Digital Analytics (GA4)',
    description: 'Page views, sessions, conversion events',
    icon: BarChart3,
    color: '#6366f1',
    dataClass: 'behavioral',
    identitiesAvailable: ['cookie_id', 'device_id', 'email'],
    ingestionMode: 'realtime',
    exampleFields: ['page_views', 'session_duration', 'last_page', 'conversions'],
    sourceCategory: 'Analytics & Measurement',
  },
  {
    id: 'attribution',
    name: 'Attribution / Measurement Logs',
    description: 'Multi-touch attribution model outputs',
    icon: BarChart3,
    color: '#6366f1',
    dataClass: 'event',
    identitiesAvailable: ['customer_id', 'click_id'],
    ingestionMode: 'batch',
    exampleFields: ['model_type', 'channel_credit', 'conversion_id', 'weight'],
    sourceCategory: 'Analytics & Measurement',
  },
  {
    id: 'experimentation',
    name: 'A/B Test / Experimentation Logs',
    description: 'Test variants, holdouts, uplift metrics',
    icon: TestTube,
    color: '#6366f1',
    dataClass: 'event',
    identitiesAvailable: ['user_id', 'device_id'],
    ingestionMode: 'batch',
    exampleFields: ['experiment_id', 'variant', 'metric_value', 'significance'],
    sourceCategory: 'Analytics & Measurement',
  },
];

// ─── Grouped by category ─────────────────────────────────────────────────────

export const SOURCE_CATEGORIES = [
  { key: 'Digital Property', label: 'Digital Properties', description: 'Behavioral & App Events', ingestionType: 'Realtime', color: '#06b6d4', badgeClass: 'badge-realtime', architectureTier: 'Data Lake' },
  { key: 'Data Infrastructure', label: 'Data Infrastructure', description: '1st Party EDW & Systems', ingestionType: 'Batch', color: '#f59e0b', badgeClass: 'badge-batch', architectureTier: 'EDW' },
  { key: 'Customer Centric', label: 'Customer-Centric', description: 'CRM, Commerce & Support', ingestionType: 'Batch', color: '#8b5cf6', badgeClass: 'badge-batch', architectureTier: 'Customer-Centric' },
  { key: 'Marketing', label: 'Marketing & Advertising', description: 'Campaigns, Ads & Email', ingestionType: 'Mixed', color: '#ec4899', badgeClass: 'badge-realtime', architectureTier: 'Data Lake' },
  { key: 'Identity & Enrichment', label: 'Identity & Enrichment', description: 'ID Graphs, Enrichment & Clean Rooms', ingestionType: 'Batch', color: '#10b981', badgeClass: 'badge-batch', architectureTier: 'EDW' },
  { key: 'Analytics & Measurement', label: 'Analytics & Measurement', description: 'GA4, Attribution & Testing', ingestionType: 'Mixed', color: '#6366f1', badgeClass: 'badge-source', architectureTier: 'Data Lake' },
];

export function getSourcesByCategory(categoryKey) {
  return SOURCE_CATALOG.filter((s) => s.sourceCategory === categoryKey);
}

export const DATA_CLASS_COLORS = {
  behavioral: { bg: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-100', label: 'Behavioral' },
  transactional: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-100', label: 'Transactional' },
  marketing: { bg: 'bg-pink-50', text: 'text-pink-700', border: 'border-pink-100', label: 'Marketing' },
  event: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-100', label: 'Event' },
};
